add version extract from git reflog

diff --git a/.github/workflows/container-image.yml b/.github/workflows/container-image.yml
--- a/.github/workflows/container-image.yml
+++ b/.github/workflows/container-image.yml
@@ -29,24 +29,35 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-        name: Checkout repository
+        name: Checkout full repository history
+        with:
+          fetch-depth: 0 # Fetch full commit history
 
       # Extract version based on trigger source (branch, tag or static)
       - name: Set IMAGE_TAG (remove 'v' prefix)
         run: |
+          set -e
           if [[ -n "${{env.TEST_IMAGE_TAG}}" && "${GITHUB_REF_NAME}" == "workflow-test" ]]; then
             echo "IMAGE_TAG=${{ env.TEST_IMAGE_TAG }}" >> $GITHUB_ENV
-            echo "IMAGE_TAG set to static value ${{ env.IMAGE_TAG }}"
+            echo "IMAGE_TAG set to ${{ env.IMAGE_TAG }} (from static workflow variable)"
           elif [[ "${GITHUB_REF_NAME}" == "main" && "${GITHUB_REF_TYPE}" == "tag" ]]; then
             # Handle tag push, extract version from the tag
             echo "IMAGE_TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
-            echo "IMAGE_TAG set to ${{ env.IMAGE_TAG }}"
+            echo "IMAGE_TAG set to ${{ env.IMAGE_TAG }} (from tag)"
           elif [[ "${GITHUB_REF_NAME}" =~ ^v.* && "${GITHUB_REF_TYPE}" == "branch" ]]; then
             # Handle feature branch (v*) push, extract version from the branch name
             echo "IMAGE_TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
-            echo "IMAGE_TAG set to ${{ env.IMAGE_TAG }}" 
-          else 
-            echo "Could not set IMAGE_TAG variable. Exit workflow."
+            echo "IMAGE_TAG set to ${{ env.IMAGE_TAG }} (from feature branch name)"
+          elif [[ "${GITHUB_REF_NAME}" == "main" && "${GITHUB_REF_TYPE}" == "branch" ]]; then
+            # Handle main branch push, extract version from git logs 
+            MERGED_BRANCH="$(git reflog show --format='%gs' -n 1 | awk '/^merge/ {print $2}' | cut -d ':' -f 1)"
+            echo "IMAGE_TAG=${MERGED_BRANCH#v}" >> $GITHUB_ENV
+            echo "IMAGE_TAG set to ${{ env.IMAGE_TAG }} (from git reflog and merge commit)"
+          fi
+
+          # Check valid version string for the IMAGE_TAG is set
+          if [[ ! "${{ env.IMAGE_TAG}}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.*)?$ ]]; then
+            echo "Could not extract valid version string for the IMAGE_TAG variable. Exiting workflow." >&2
             exit 1
           fi
 
